### ISSUE TITLE
Password Encryption w/bcrypt 

### ISSUE THREAD

**Issue by hugoLucas** [mattlevan/toro-net#10]
## Problem 
Currently, passwords are stored in plain text. We need to encrypt/hash passwords in the front-end and compare those hashes to those stored in the database. 

## Other Info
For more information on bcrypt see [this](https://www.npmjs.com/package/bcrypt).

**Comment by FlyBono24** [comment]
I'd like to take a _crack_ at this one (pun intended)

**Comment by mattlevan** [comment]
Assigning this to @FlyBono24, thanks for taking the initiative.

**Comment by mattlevan** [comment]
Let's get this done @FlyBono24 @nolanruss!

**Comment by mattlevan** [comment]
# Pseudocode
## Registration
1. Accept valid password input from user in plain text (registration form)
2. Hash the password with salted algorithm (`bcrypt.genSalt()` and `bcrypt.hash`)
3. Store the hash in the user database
4. Do *not* save the plain text password anywhere for any reason

## Login
1. Accept valid password input from user in plain text (login form)
2. Compare plain password with hash (`bcrypt.compare()`) to determine if access is to be granted

**Comment by mattlevan** [comment]
This was really easy to implement using [bcryptjs](https://github.com/mattlevan/toro-net/commit/a3d197ab8947cd7b1a4aaab8fc695428ce5498f4), so I've done it with the latest commit mattlevan/toro-net@a3d197ab8947cd7b1a4aaab8fc695428ce5498f4.

**Comment by FlyBono24** [comment]
I got the first half working, still working on decrypting it... following the steps I found in some tutorial but it's not working, gotta massage the code a little.

**Comment by FlyBono24** [comment]
Oh that was much easier than the one I Found... cool...

**Comment by mattlevan** [comment]
Hey @FlyBono24 check out my above comment, was a total of ~3 lines I think! `bcryptjs` basically did everything for us.

**Comment by FlyBono24** [comment]
I think the link I found was using the bcrypt-nodejs package and it was
about 10 lines of code.  It didn't recognize where I was passing in
"password" into the method though so I didn't get it to work.  good to see
it was easier with bcrypt!
