### ISSUE TITLE
Username vs. email for unique identifier

### ISSUE THREAD

**Issue by mattlevan** [mattlevan/toro-net#9]
# Issue
We must soon decide to use either `username` or `email` as our unique identifier in our MongoDB users collection, so let's list the potential issues with each. Please comment below with additional comments and/or concerns.

# Analysis
### Pros
* GitHub (and most other OAuth2 services) always return it
### Cons
* Collisions can occur as usernames tend to repeat across OAuth2 services (in the case we implement additional login methods such as Facebook, Google, etc.)
* Non-standard (most Internet apps use email)

### Scenarios with `username` as unique identifier
For the following scenarios, assume each one begins with a completely empty users collection in the database.

1. **No username returned from OAuth2 service**  
  a. User logs in with third-party
  b. Third-party does not provide username with return payload
  c. MongoDB throws a user validation error-- no username provided!
  d. User is free to register with username of his choosing using our app's registration form

2. **Username successfully returned from OAuth2 service**  
  a. User logs in with third-party
  b. Third-party provides username with return payload
  c. User is now authenticated, his profile is written to the database with corresponding username
  d. User may *not* register using that same username using our app's registration form

3. **User registers with username using our app's registration form**  
  a. User fills out registration form with valid data
  b. Successful registration; his profile is written to the database with corresponding username
  c. User attempts to now authenticate using third-party service:  
  d. If same username is present in third-party return payload, login via third-party hangs and we must implement a more graceful handling  
  e. If different username is present, technically a new user is now registered in our database
  f. If *no* username is returned, MongoDB throws a user validation error-- no username provided!  

I believe these scenarios cover most cases; please add another if you think otherwise! 

### `username` insights
* We *must* require `username` from third-party services, otherwise no auth allowed
* Too easy for single humans to register multiple accounts (very weak validation)

### Pros
* Standard unique identifier across the web
* Potential for validation via email confirmation
### Cons
* OAuth2 services do not always provide it

It seems that using `email` as our unique id is the best way to go simply because collision is less likely.

### Scenarios with `email` as unique identifier
For the following scenarios, assume each one begins with a completely empty users collection in the database.

1. **No email returned from OAuth2 service**  
  a. User logs in with third-party
  b. Third-party does not provide email with return payload
  c. MongoDB throws a user validation error-- no email provided!
  d. User is free to register with email of his choosing using our app's registration form

2. **Email successfully returned from OAuth2 service**  
  a. User logs in with third-party
  b. Third-party provides email with return payload
  c. User is now authenticated, his profile is written to the database with corresponding email
  d. User may *not* register using that same email using our app's registration form

3. **User registers with email using our app's registration form**  
  a. User fills out registration form with valid data
  b. Successful registration; his profile is written to the database with corresponding email
  c. User attempts to now authenticate using third-party service:  
  d. If same email is present in third-party return payload, login via third-party hangs and we must implement a more graceful handling  
  e. If different email is present, technically a new user is now registered in our database
  f. If *no* email is returned, MongoDB throws a user validation error-- no email provided!  

I believe these scenarios cover most cases; please add another if you think otherwise! 

### `email` insights
* We *must* require `email` from third-party services, otherwise no auth allowed
* We keep opportunities open for email-dependent features:
  * Forgot password?
  * Email confirmation for user validation
* Our app is more standard, when compared to rest of the Internet
* One human may register multiple accounts, given he uses unique emails for each
* Extra third-party configuration (minimal) is required to ensure email is returned; and, if not, prohibit user from authenticatin with that service

# Takeaways
## Email is the way to go 
We can configure GitHub (and other OAuth2 services, should we add them in the future) to return email; if it doesn't, the user must simply register using our form.

**Comment by FlyBono24** [comment]
For Registration why don't we make both unique?  That way we can support all Oauth services, if we implement Facebook, Google, any others going forward.
In this context, this is _only_ referring to the Unique ID for the Mongo collection, correct?  In that case I would vote for Email

**Comment by mattlevan** [comment]
@flybono24 this is not a bad idea but I'm fairly certain that each mongodb collection may have maximum one index, therefore we will have to choose username or email, not both. Reference here: http://mongoosejs.com/docs/2.7.x/docs/schematypes.html

**Comment by Alexander-Ing** [comment]
I also vote for email as it is industry standard,

Is it not possible to have both the username and email unique but use some auto-generated number for internal indexing? or as hugo suggested yesterday a compound unique index? 

example:
https://docs.mongodb.com/manual/core/index-unique/

**Comment by FlyBono24** [comment]
@mattlevan Correct, I was referring to the context of the MongoDB... 
Are we storing a token or anything for Github login right now?  Doesn't look like we are.  Here's a good read on securing our db from Security stackexchange, if we wanted to go that route: 
https://security.stackexchange.com/questions/72475/should-we-store-accesstoken-in-our-database-for-oauth2

**Comment by mattlevan** [comment]
According to the MongoDB doc linked by @Alexander-Ing, using a compound unique index would mean that, technically, the two following users would be distinct!

{ username: 'm', email: 'm@m.com' }
{ username: 'k', email: 'm@m.com' }

The reason this is true is because of the following, copied straight from the doc linked by Alex: 

> You can also enforce a unique constraint on compound indexes. If you use the unique constraint on a compound index, then MongoDB will enforce uniqueness on the combination of the index key values.

This is, of course, not what we want.

**Comment by FlyBono24** [comment]
@Alexander-Ing I was just reading about Compound Indexes on your link and I agree with @mattlevan , this would break our email uniqueness.
We should use email for our MongoDB Unique ID, and maybe we could enforce a unique username within the code itself

**Comment by nolanruss** [comment]
It looks like we can have more than 1 index for our documents in MongoDB [(MongoDB limits)](https://docs.mongodb.com/manual/reference/limits/).  We can require unique usernames and email addresses, and then provide auth options.  We can add a field for the token response  to the user schema.

**Comment by mattlevan** [comment]
Closed with [this commit](https://github.com/mattlevan/toro-net/commit/f968bbdc60bd62409e70aec5d8af0be13f8643ac).
